version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./etc/:/etc/nginx/
      - ./pki/:/etc/pki/
      - logs-data:/etc/nginx/logs
    external_links:
      - wordpress
    networks:
      - frontend-network
    healthcheck:
      test: 'curl -k --connect-timeout 5 --silent https://127.0.0.1 || exit 1'
networks:
  frontend-network:
    external:
      name: frontend-network

volumes:
  logs-data:
