version: "3.8"

# 1)密码由 .env 存放
# 2)密码存放在 secrets: $ printf <secret> | docker secret create mariadb_secret -
#
services:
  mariadb:
    container_name: mariadb-server
    restart: always
    hostname: mariadb
    image: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD
    healthcheck:
      test: 'echo "SELECT version();"| mysql -uroot -h localhost -p$$MYSQL_ROOT_PASSWORD'
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - backbone-network

networks:
  backbone-network:
    external:
      name: backbone-network

volumes:
  mariadb-data:
